### ISSUE TITLE
Disable 1722.1 protocol in XMOS AVB Endpoint Software 6.1.1

### ISSUE THREAD

**Issue by Chandini212** [xmos/lib_tsn#22]
Hi,

I purchased an XMOS AVB Endpoint Kit in February 2015. It contained factory firmware version 5.0 (does not support 1722.1 protocol). On building and flashing app_avb_lc_demo in firmware 6.1.1, wireshark logs show that it runs 1722.1 protocol and controller. Since I was working on v5.0 which does not support 1722.1, I was trying to disable 1722.1 protocol in v6.1.1 by setting AVB_ENABLE_1722_1 in avb_conf.h to 0. But, during build, following error was observed -

C:/Users/cchandini/workspace/module_avb/src/avb.xc:573:9: error: unknown function identifier `avb_1722_1_process_packet' (possibly missing prototype?)

On commenting this function call, more build errors were observed -

C:/Users/cchandini/workspace/module_avb_1722_1/src/avb_1722_1_adp.xc: Error: Undefined reference to 'avb_entity_on_new_entity_available'
C:/Users/cchandini/workspace/module_avb_1722_1/src/avb_1722_1_acmp_periodic.xc: Error: Undefined reference to 'avb_listener_on_talker_connect'
C:/Users/cchandini/workspace/module_avb_1722_1/src/avb_1722_1_acmp_periodic.xc: Error: Undefined reference to 'avb_listener_on_talker_disconnect'
C:/Users/cchandini/workspace/module_avb_1722_1/src/avb_1722_1_acmp_periodic.xc: Error: Undefined reference to 'avb_talker_on_listener_connect'
C:/Users/cchandini/workspace/module_avb_1722_1/src/avb_1722_1_acmp_periodic.xc: Error: Undefined reference to 'avb_talker_on_listener_connect_failed'
C:/Users/cchandini/workspace/module_avb_1722_1/src/avb_1722_1_acmp_periodic.xc: Error: Undefined reference to 'avb_talker_on_listener_disconnect'
C:/Users/cchandini/workspace/module_avb_1722_maap/src/avb_1722_maap.xc: Error: Undefined reference to 'avb_talker_on_source_address_reserved'

Is there any clean and easy way to disable 1722.1 protocol in v6.1.1 ?
Also, is v5.0 firmware available for download anywhere? Help required asap.

Thanks!

**Comment by larry-xmos** [comment]
Thank you for your report. Could you try `AVB_1722_1_CONTROLLER_ENABLED`? I'll close this issue now, because the repository is for the newer version 7 of AVB/TSN. Please post back any comments on the original forum thread at http://www.xcore.com/forum/viewtopic.php?f=47&t=4863.
